// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bK0tQ6Wax4foLR33af8gg8EZ6YQ6CzM',
    appId: '1:2914622177:web:00996fdea3e68db59b75a0',
    messagingSenderId: '2914622177',
    projectId: 'notes-flutter-50640',
    authDomain: 'notes-flutter-50640.firebaseapp.com',
    databaseURL: 'https://notes-flutter-50640-default-rtdb.firebaseio.com',
    storageBucket: 'notes-flutter-50640.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_Zs2ih4K1MT_tzJuZNLnx9hOfsyxi24',
    appId: '1:2914622177:android:a34678d5d84e34389b75a0',
    messagingSenderId: '2914622177',
    projectId: 'notes-flutter-50640',
    databaseURL: 'https://notes-flutter-50640-default-rtdb.firebaseio.com',
    storageBucket: 'notes-flutter-50640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDekAclZnbUJVCc0CS2lSIoqpF2A9iidPk',
    appId: '1:2914622177:ios:c18c750650302f159b75a0',
    messagingSenderId: '2914622177',
    projectId: 'notes-flutter-50640',
    databaseURL: 'https://notes-flutter-50640-default-rtdb.firebaseio.com',
    storageBucket: 'notes-flutter-50640.firebasestorage.app',
    iosBundleId: 'com.example.notesAppWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDekAclZnbUJVCc0CS2lSIoqpF2A9iidPk',
    appId: '1:2914622177:ios:c18c750650302f159b75a0',
    messagingSenderId: '2914622177',
    projectId: 'notes-flutter-50640',
    databaseURL: 'https://notes-flutter-50640-default-rtdb.firebaseio.com',
    storageBucket: 'notes-flutter-50640.firebasestorage.app',
    iosBundleId: 'com.example.notesAppWithFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8bK0tQ6Wax4foLR33af8gg8EZ6YQ6CzM',
    appId: '1:2914622177:web:e75a9ee25e5473d79b75a0',
    messagingSenderId: '2914622177',
    projectId: 'notes-flutter-50640',
    authDomain: 'notes-flutter-50640.firebaseapp.com',
    databaseURL: 'https://notes-flutter-50640-default-rtdb.firebaseio.com',
    storageBucket: 'notes-flutter-50640.firebasestorage.app',
  );
}
